<?php

return array(
        'DEFAULT_CHANNEL_PREFIX' => 'gemmap_',//默认频道前缀
        'TEMPLATE_PATH' => 'Template/default',//默认模板路径
        'CHANNEL_THEME_TEMPLATE_PATH' => 'TemplateChannel/',//频道主题模板路径

        'URL_HTML_SUFFIX' => '',  // URL伪静态后缀设置
        // 'OUTPUT_ENCODE' =>  true, //页面压缩输出支持   配置了 没鸟用
        'PAYMENT_PLUGIN_PATH' => PLUGIN_PATH . 'payment',
        'LOGIN_PLUGIN_PATH' => PLUGIN_PATH . 'login',
        'SHIPPING_PLUGIN_PATH' => PLUGIN_PATH . 'shipping',
        'FUNCTION_PLUGIN_PATH' => PLUGIN_PATH . 'function',
        'SHOW_PAGE_TRACE' => false,
        'CFG_SQL_FILESIZE' => 5242880,
        //'URL_MODEL'=>1, //
        //默认错误跳转对应的模板文件
        'TMPL_ACTION_ERROR' => 'Public:dispatch_jump',
        //默认成功跳转对应的模板文件
        'TMPL_ACTION_SUCCESS' => 'Public:dispatch_jump',

        'seo_title' => '广州京墨医疗科技有限公司',
        'seo_keyword' => '广州京墨医疗科技有限公司',
        'seo_description' => '广州京墨医疗科技有限公司',

        //建表初始字段
        //1_ARTICLE: 资讯表
        'TABLE_FIELD_1_ARTICLE' => '[{"control_type":"text","control_label":"标题","control_field":"title","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"image","control_label":"封面地址","control_field":"cover_url","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":2},{"control_type":"text","control_label":"外部链接","control_field":"link","control_verify":"","control_default":"","control_required":"0","order":3},{"control_type":"textarea","control_label":"摘要","control_field":"desc","control_verify":"","control_height":"100px","control_default":"","control_required":"0","order":4},{"control_type":"texteditor","control_label":"内容","control_field":"content","control_verify":"","control_height":"200px","control_default":"","control_required":"0","order":5}]',

        //1_ACTIVITY: 活动表
        'TABLE_FIELD_1_ACTIVITY' => '[{"control_type":"text","control_label":"标题","control_field":"title","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"textarea","control_label":"摘要","control_field":"desc","control_verify":"","control_height":"100px","control_default":"","control_required":"0","order":2},{"control_type":"texteditor","control_label":"内容","control_field":"content","control_verify":"","control_height":"200px","control_default":"","control_required":"0","order":3},{"control_type":"text","control_label":"主办方","control_field":"sponsor","control_verify":"","control_default":"","control_required":"0","order":4},{"control_type":"image","control_label":"主办方图标","control_field":"sponsor_logo_url","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":5},{"control_type":"text","control_label":"活动费用","control_field":"cost","control_verify":"Double","control_default":"","control_required":"0","order":6},{"control_type":"textarea","control_label":"活动地址","control_field":"address","control_verify":"","control_height":"200px","control_default":"","control_required":"0","order":7},{"control_type":"image","control_label":"封面地址","control_field":"cover_url","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":8},{"control_type":"datetime","control_label":"报名开始时间","control_field":"plan_start_time","control_verify":"","control_default":"","control_required":"0","order":9},{"control_type":"datetime","control_label":"报名截止时间","control_field":"plan_end_time","control_verify":"","control_default":"","control_required":"0","order":10},{"control_type":"datetime","control_label":"活动开始时间","control_field":"formal_start_time","control_verify":"","control_default":"","control_required":"0","order":11},{"control_type":"datetime","control_label":"活动截止时间","control_field":"formal_end_time","control_verify":"","control_default":"","control_required":"0","order":12},{"control_type":"text","control_label":"外部链接","control_field":"link","control_verify":"","control_default":"","control_required":"0","order":13}]',

        //1_COMPANY：企业表
        // 'TABLE_FIELD_1_COMPANY' => '[{"control_type":"text","control_label":"公司名称	","control_field":"title","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"image","control_label":"LOGO","control_field":"logo_img","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":2},{"control_type":"text","control_label":"官方网站	","control_field":"site_link","control_verify":"","control_default":"","control_required":"0","order":3},{"control_type":"text","control_label":"联系人姓名	","control_field":"contacts","control_verify":"","control_default":"","control_required":"0","order":4},{"control_type":"text","control_label":"联系手机	","control_field":"mobile","control_verify":"Mobile","control_default":"","control_required":"0","order":5},{"control_type":"text","control_label":"联系人邮箱	","control_field":"email","control_verify":"Email","control_default":"","control_required":"0","order":6},{"control_type":"image","control_label":"营业执照照片	","control_field":"license_img","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":7},{"control_type":"text","control_label":"公司地址	","control_field":"address","control_verify":"","control_default":"","control_required":"0","order":8},{"control_type":"texteditor","control_label":"公司简介	","control_field":"intro","control_verify":"","control_height":"200px","control_default":"","control_required":"0","order":9},{"control_type":"cityselect","control_label":"地域","control_field":"city","control_verify":"","control_default":"","control_required":"0","order":10},{"control_type":"text","control_label":"企业账号	","control_field":"company_account","control_verify":"","control_default":"","control_required":"0","order":11},{"control_type":"password","control_label":"企业密码	","control_field":"company_pw","control_verify":"","control_default":"","control_required":"0","order":12}]',
        'TABLE_FIELD_1_COMPANY' => '[{"control_type":"text","control_label":"\u516c\u53f8\u540d\u79f0\t","control_field":"title","control_verify":"","control_default":"","control_required":"0","order":3},{"control_type":"text","control_label":"\u516c\u53f8\u5730\u5740\t","control_field":"address","control_verify":"","control_default":"","control_required":"0","order":4},{"control_type":"text","control_label":"\u8054\u7cfb\u4eba\u59d3\u540d\t","control_field":"contacts","control_verify":"","control_default":"","control_required":"0","order":5},{"control_type":"text","control_label":"\u8054\u7cfb\u624b\u673a\t","control_field":"mobile","control_verify":"Mobile","control_default":"","control_required":"0","order":6},{"control_type":"text","control_label":"\u8054\u7cfb\u4eba\u90ae\u7bb1\t","control_field":"email","control_verify":"Email","control_default":"","control_required":"0","order":7},{"control_type":"text","control_label":"\u5b98\u65b9\u7f51\u7ad9\t","control_field":"site_link","control_verify":"","control_default":"","control_required":"0","order":8},{"control_type":"cityselect","control_label":"\u670d\u52a1\u5730\u57df","control_field":"city","control_verify":"","control_default":"","control_required":"0","order":9},{"control_type":"image","control_label":"\u4f01\u4e1aLOGO","control_field":"logo_img","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":10},{"control_type":"image","control_label":"\u8425\u4e1a\u6267\u7167\u7167\u7247\t","control_field":"license_img","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":11},{"control_type":"texteditor","control_label":"\u516c\u53f8\u7b80\u4ecb\t","control_field":"intro","control_verify":"","control_height":"200px","control_default":"","control_required":"0","order":12}]',

        //2：分类
        'TABLE_FIELD_2' => '[{"control_type":"text","control_label":"类别名称","control_field":"cat_name","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"text","control_label":"英文名称","control_field":"call_index","control_verify":"","control_default":"","control_required":"0","order":2},{"control_type":"image","control_label":"显示图片","control_field":"cat_img","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":3},{"control_type":"text","control_label":"排序数字","control_field":"sort_num","control_verify":"Num","control_default":"","control_required":"0","order":4}]',

        //3. 活动订单
        'TABLE_FIELD_3' => '[{"control_type":"textarea","control_label":"活动名称","control_field":"activity_name","control_verify":"","control_height":"100px","control_default":"","control_required":"0","order":1},{"control_type":"datetime","control_label":"活动开始时间","control_field":"activity_start_time","control_dateformat":"date","control_default":"","control_required":"0","order":2},{"control_type":"datetime","control_label":"活动结束时间","control_field":"activity_end_time","control_dateformat":"date","control_default":"","control_required":"0","order":3}]',
        //3_COMPANY: 公司级别
        'TABLE_FIELD_3_COMPANY' => '[{"control_type":"text","control_label":"级别名称","control_field":"level_name","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"select","control_label":"级别顺序","control_field":"jibieshunxu","control_item":[{"identify":"6751690471855392","color":"color_a","name":"1","defaults":"0"},{"identify":"7108147330196835","color":"color_a","name":"2","defaults":"0"},{"identify":"9014843254886595","color":"color_a","name":"3","defaults":"0"},{"identify":"8320818380348696","color":"color_a","name":"4","defaults":"0"},{"identify":"8350081471931263","color":"color_a","name":"5","defaults":"0"},{"identify":"6975388271280765","color":"color_a","name":"6","defaults":"0"},{"identify":"08211187757261218","color":"color_a","name":"7","defaults":"0"},{"identify":"9051566710976413","color":"color_a","name":"8","defaults":"0"},{"identify":"9800576074190632","color":"color_a","name":"9","defaults":"0"}],"control_required":"0","order":2},{"control_type":"text","control_label":"费用","control_field":"cost","control_verify":"Double","control_default":"","control_required":"0","order":3},{"control_type":"text","control_label":"有效期","control_field":"expiry_date","control_verify":"Num","control_default":"","control_required":"0","order":4}]',

        //4. 标签
        'TABLE_FIELD_4' => '[{"control_type":"text","control_label":"标签名称","control_field":"tag_name","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"text","control_label":"标签描述","control_field":"remark","control_verify":"","control_default":"","control_required":"0","order":2},{"control_type":"text","control_label":"排序数字","control_field":"sort_num","control_verify":"","control_default":"","control_required":"0","control_is_mobile":"0","control_is_admin":"0","order":3}]',
        //5 为标签关系表，特殊处理

        //6_COMPANY. 企业招聘信息
        'TABLE_FIELD_6_COMPANY' => '[{"control_type":"text","control_label":"岗位名称","control_field":"title","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"text","control_label":"工作职责","control_field":"obligation","control_verify":"","control_default":"","control_required":"0","order":2},{"control_type":"text","control_label":"薪酬范围","control_field":"payment","control_verify":"","control_default":"","control_required":"0","order":3},{"control_type":"text","control_label":"联系人","control_field":"contacts","control_verify":"","control_default":"","control_required":"0","order":4},{"control_type":"text","control_label":"联系邮箱","control_field":"email","control_verify":"Email","control_default":"","control_required":"0","order":5},{"control_type":"text","control_label":"联系电话","control_field":"phone","control_verify":"","control_default":"","control_required":"0","order":6},{"control_type":"texteditor","control_label":"简介","control_field":"intro","control_verify":"","control_height":"200px","control_default":"","control_required":"0","order":7},{"control_type":"select","control_label":"\u5b66\u5386\u8981\u6c42","control_field":"xlk","control_item":[{"identify":"4197209226309575","color":"color_a","name":"\u5927\u4e13\u6216\u4ee5\u4e0b","defaults":"0"},{"identify":"768184491742562","color":"color_a","name":"\u672c\u79d1","defaults":"0"},{"identify":"2511871327891786","color":"color_a","name":"\u7855\u58eb","defaults":"0"},{"identify":"6808529222448252","color":"color_a","name":"\u535a\u58eb\u53ca\u4ee5\u4e0a","defaults":"0"}],"control_required":"0","control_is_mobile":"0","control_is_admin":"0","order":8},{"control_type":"text","control_label":"\u7ecf\u9a8c\u8981\u6c42","control_field":"jyyq","control_verify":"Num","control_default":"","control_required":"0","control_is_mobile":"0","control_is_admin":"0","order":9},{"control_type":"text","control_label":"\u804c\u4f4d\u8bf1\u60d1","control_field":"zwyh","control_verify":"","control_default":"","control_required":"0","control_is_mobile":"0","control_is_admin":"0","order":10},{"control_type":"cityselect","control_label":"\u5de5\u4f5c\u5730\u70b9","control_field":"gzdd","control_verify":"","control_default":"","control_required":"0","control_is_mobile":"0","control_is_admin":"0","order":11}]',
        //6_ACTIVITY：票务类型
        'TABLE_FIELD_6_ACTIVITY' => '[{"control_type":"text","control_label":"类型名称","control_field":"cat_name","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"text","control_label":"类型描述","control_field":"desc","control_verify":"","control_default":"","control_required":"0","order":2},{"control_type":"image","control_label":"显示图片","control_field":"cat_img","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":3},{"control_type":"text","control_label":"票价","control_field":"ticket_price","control_verify":"Double","control_default":"","control_required":"0","order":4},{"control_type":"text","control_label":"返还比例","control_field":"ticket_return_ratio","control_verify":"Double","control_default":"","control_required":"0","order":5},{"control_type":"text","control_label":"排序数字","control_field":"sort_num","control_verify":"Num","control_default":"","control_required":"0","order":6}]',

        //7_COMPANY：企业资料
        'TABLE_FIELD_7_COMPANY' => '[{"control_type":"text","control_label":"资料名称","control_field":"title","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"image","control_label":"封面图片","control_field":"cover_img","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":2},{"control_type":"upload","control_label":"存档文件","control_field":"file_path","control_fileformat":"doc,xls,ppt,pdf","control_required":"0","order":3},{"control_type":"textarea","control_label":"摘要","control_field":"remark","control_verify":"","control_height":"100px","control_default":"","control_required":"0","order":4}]',

        //8_COMPANY: 企业动态
        'TABLE_FIELD_8_COMPANY' => '[{"control_type":"text","control_label":"标题","control_field":"title","control_verify":"","control_default":"","control_required":"0","order":1},{"control_type":"image","control_label":"封面地址","control_field":"cover_url","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":2},{"control_type":"text","control_label":"外部链接","control_field":"link","control_verify":"","control_default":"","control_required":"0","order":3},{"control_type":"textarea","control_label":"摘要","control_field":"desc","control_verify":"","control_height":"100px","control_default":"","control_required":"0","order":4},{"control_type":"texteditor","control_label":"内容","control_field":"content","control_verify":"","control_height":"200px","control_default":"","control_required":"0","order":5}]',

        //9_COMPANY: 招聘分类
        'TABLE_FIELD_9_COMPANY' => '[{"control_type":"select","control_label":"父类","control_field":"parent_id","control_item":[],"control_required":"0","order":1},{"control_type":"text","control_label":"分类名称","control_field":"title","control_verify":"","control_default":"","control_required":"0","order":2},{"control_type":"text","control_label":"描述","control_field":"desc","control_verify":"","control_default":"","control_required":"0","order":3},{"control_type":"image","control_label":"封面","control_field":"cover_url","control_fileformat":"jpg,gif,png,bmp","control_required":"0","order":4},{"control_type":"text","control_label":"排序","control_field":"sort","control_verify":"","control_default":"","control_required":"0","order":5}]',
        //site_name_check新建子站时不可为子站名的名称
        'site_name_check' => array('service', 'jingmo', 'gemmap', 'admin', 'user', 'global', 'test', 'delete', 'update', '5u'),
    
        //yewu_data_module_type业务数据里面包含的模块
        'yewu_data_module_type' => array('Article','Activity','Company'),

        //拥有订单/报名表的频道模块类型
        'haveOrder' => array('Activity'),

        //频道基础模块建表流程控制
        'ARTICLE_FLOW' => array(1, 2, 4, 5),
        'ACTIVITY_FLOW' => array(1, 2, 3, 4, 5, 6),
        'COMPANY_FLOW' => array(1, 2, 3, 4, 5, 6, 7, 8, 9),

        //频道菜单
        'ARTICLE_MENU_SET' => array(1, 2, 4,10),
        'ACTIVITY_MENU_SET' => array(1, 2, 4, 10),
        'COMPANY_MENU_SET' => array(1, 2, 3, 4, 9,10),
);